# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target 'CT_RESTAPI_Example’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxAlamofire'
pod 'ObjectMapper'
pod 'SwiftyJSON'
pod 'RxSwift'
pod 'CocoaLumberjack/Swift'
pod 'CT_RESTAPI', :path => 'LocalPods/CT_RESTAPI/'

end
